// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EnglishWords: typeof import('./components/EnglishWords.vue')['default']
    XiaoHeKeyboard: typeof import('./components/XiaoHeKeyboard.vue')['default']
  }
}

export { }
